/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Gusanito;

/*
 * SNAKE
 * Very basic example of the snake game.
 * by Guillermo Sampallo - 2019
 * www.gsampallo.com
 */

public class App{
    
    public static void main(String[] args) {
            Game newGame = new Game();
	}

}